### ISSUE TITLE
Follow up Action - Show Message editing failed

### ISSUE THREAD

**Issue by Alex-Schulte** [sitegeist/Sitegeist.PaperTiger#9]
When adding the "show message" action to a form and try to edit the message text in the neos ui backend it fails (with a blank page) and throws a js error.
Tested with Neos 8.2.5 and Neos UI 8.3.0

`TypeError: Cannot read properties of undefined (reading 'hyphens')
    at Object.isVisible (Plugin.js?2ce97fec:1:11095)
    at isToolbarItemVisible.js:6:36
    at renderToolbarComponents.js:24:83
    at Array.filter (<anonymous>)
    at ru.renderToolbarComponents (renderToolbarComponents.js:22:14)
    at ru.render (EditorToolbar.js:41:48)
    at GZ (react-dom.production.min.js:182:192)
    at Lde (react-dom.production.min.js:181:224)
    at Rpe (react-dom.production.min.js:263:490)
    at Lpe (react-dom.production.min.js:246:265)`
    
I could fix this by adding editorOptions with a buttonLabel to the message property. But not sure, if this is a "real" fix ;)

`message:
      ui:
        inspector:
          editorOptions:
            buttonLabel: "Nachricht"`

**Comment by mficzel** [comment]
Can you try this in Neos 8.3 ... pretty sure this worked for me

**Comment by Alex-Schulte** [comment]
I double checked it with Neos 8.3.4 and the latest updates from here.
And it's been working without the fix for Neos 8.2.5
